Added different sizes to chip component
scality/core-ui pull request #104
Opened 2019-10-22 18:03 UTC by edumoreira1506

**Component**: Chips

**Description**: Before the chips component had just one size. Now have 4 options.

**Design**: 
![Screenshot from 2019-10-22 15-00-11](https://user-images.githubusercontent.com/49662698/67315444-fad8b780-f4dc-11e9-824e-385b70564229.png)

Closes: #99

2019-10-23 15:50 UTC, carlito-scality requested changes

2019-10-23 15:50 UTC, carlito-scality commented on src/lib/components/chips/Chips.component.js
> +import type { Variant, LoaderSize } from "../constants";
It is a good a idea to use `LoaderSize` but the we should rename it to `Size` in `constant.js`

2019-10-23 15:50 UTC, carlito-scality commented on src/lib/components/chips/Chips.component.js
> +          font-size: ${defaultTheme.fontSize.smaller};
We should have to the same mapping between `props.size` and `defaultTheme.fontSize`to be consistent.

=> `font-size: ${defaultTheme.fontSize[props.size]};`

2019-10-23 15:50 UTC, carlito-scality commented on src/lib/components/chips/Chips.component.js
` border-radius` should be based on the `props.size` to be neat.

2019-10-23 15:50 UTC, carlito-scality commented on src/lib/components/chips/Chips.component.js
idem for `border-radius: 15px;` and `padding: 7px 8px;` of ChipsIcon

2019-10-23 15:50 UTC, carlito-scality commented on src/lib/components/chips/Chips.component.js
> +          height: 40px;
`height`and `width` should be removed since they are necessary here

2019-10-23 17:51 UTC, edumoreira1506 commented on src/lib/components/chips/Chips.component.js
> +import type { Variant, LoaderSize } from "../constants";
I added `Size` in `constant.js` I could not rename, because is used in other files too.

2019-10-23 18:04 UTC, carlito-scality commented on src/lib/components/chips/Chips.component.js
> +import type { Variant, LoaderSize } from "../constants";
Yes you could :) since we should have only one type for the  Size. Like that,  you rename it where it is used.

2019-10-24 14:55 UTC, edumoreira1506 commented
I believe that now, everything is ok! Look:
![Screenshot from 2019-10-24 11-54-17](https://user-images.githubusercontent.com/49662698/67497989-254d8080-f655-11e9-945d-ea83b74f14ca.png)

2019-10-30 14:01 UTC, carlito-scality commented
Merged in https://github.com/scality/core-ui/pull/111

2019-10-30 14:01 UTC, closed without merging