Theme: support dark/light modes
scality/core-ui pull request #110
Opened 2019-10-28 11:24 UTC by carlito-scality

**Component**:Theme

**Description**:
- Update all component color (background-color, color, border-color...) based on new color palette
- In the theme.js, we define a default light mode's colors palette, but It is up to user to define their own palette.
- This color palette is to be improved later by our UX team.

**Design**:

**Breaking Changes**:

- [] Breaking Changes

---

Closes: https://github.com/scality/core-ui/issues/105

2019-10-28 11:24 UTC, bert-e commented
# Hello carlito-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/core-ui/bert-e/doc/user).





*Status report is not available.*

2019-10-28 11:24 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @chengyanjin

* @rachedbenmustapha

* @nicolas2bert

* @monpote

2019-10-30 08:12 UTC, ChengYanJin requested changes
Some small improvement, please.

2019-10-30 08:12 UTC, ChengYanJin commented on stories/tooltip.js
> +          <SubTitle>Hover here!</SubTitle>
I think we should create another wrapper `<Text>` instead of `<SubTitle>`. 
For the single text, we don't need to use `<h3>` or `<h4>`, so that the tooltip can have the same padding in four different positions (left, right, top, bottom)

2019-10-30 08:12 UTC, ChengYanJin commented on stories/loader.js
> +      </Wrapper>
We need to add a wrapper for text as well. As we can see from the storybook, the color of {content} is still black in the Dark Theme.

2019-10-30 08:12 UTC, ChengYanJin commented on src/lib/components/searchinput/SearchInput.component.js
>      }
we need to set the background color of `input:-internal-autofill-selected `
Otherwise, when we choose something from the autofill list, the input background-color will be changed to white.

2019-10-30 08:12 UTC, ChengYanJin commented on stories/chips.js
>      <div className="storybook-chips">
We need to use <Wrapper> as well in order to change the theme :)

2019-10-30 08:12 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @chengyanjin

* @rachedbenmustapha

* @nicolas2bert

* @monpote





The following reviewers are expecting changes from the author, or must review again:

* @chengyanjin

2019-10-30 10:39 UTC, ChengYanJin approved these changes
LGTM!

2019-10-30 10:40 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @chengyanjin

* @rachedbenmustapha

* @nicolas2bert

* @monpote

2019-10-30 10:45 UTC, carlito-scality commented
@bert-e approve

2019-10-30 10:45 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-10-30 10:45 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue None.

Goodbye carlito-scality.

2019-10-30 10:45 UTC, merged