Merge chip support diffrent sizes
scality/core-ui pull request #111
Opened 2019-10-29 14:01 UTC by carlito-scality

**Component**:Merge

**Description**:
- Merge open source PR https://github.com/scality/core-ui/pull/104

**Design**:

**Breaking Changes**:

- [] Breaking Changes

---

Closes: https://github.com/scality/core-ui/issues/99

2019-10-29 14:01 UTC, bert-e commented
# Hello carlito-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/core-ui/bert-e/doc/user).





*Status report is not available.*

2019-10-29 14:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @chengyanjin

* @rachedbenmustapha

* @nicolas2bert

* @monpote

2019-10-29 14:05 UTC, carlito-scality commented
@edumoreira1506 Hi :) I just pushed a commit to improve some styles. Let me know if it is ok for you.

2019-10-29 14:07 UTC, edumoreira1506 commented
Nice! It's ok!

2019-10-29 14:10 UTC, carlito-scality commented
> Nice! It's ok!

Thanks :)

2019-10-30 09:28 UTC, ChengYanJin requested changes

2019-10-30 09:28 UTC, ChengYanJin commented on src/lib/components/chips/Chips.component.js
> +      color: ${defaultTheme.gray};
We should not use ${defaultTheme.gray}. If it's a gray Chip, the `remove icon` disappears when you hover.
I will let you address it after merging the dark/light mode PR.

2019-10-30 09:28 UTC, ChengYanJin commented on src/lib/components/chips/Chips.component.js
> +          inverted={true}
I guess we don't need `inverted` prop in Chips component. :)

2019-10-30 09:28 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @chengyanjin

* @rachedbenmustapha

* @nicolas2bert

* @monpote





The following reviewers are expecting changes from the author, or must review again:

* @chengyanjin

2019-10-30 13:56 UTC, ChengYanJin approved these changes
LGTM!

2019-10-30 13:56 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @chengyanjin

* @rachedbenmustapha

* @nicolas2bert

* @monpote

2019-10-30 13:59 UTC, carlito-scality commented
@bert-e approve

2019-10-30 13:59 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-10-30 14:00 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue None.

Goodbye carlito-scality.

2019-10-30 14:00 UTC, merged