Dropdown: Add cursor pointer to DropdownStyled
scality/core-ui pull request #129
Opened 2019-11-12 11:20 UTC by ChengYanJin

**Component**:Dropdown

**Description**:
When hover to the dropdown it's better to show the pointer so that the user can understand it's clickable.

**Design**:

2019-11-12 11:20 UTC, bert-e commented
# Hello chengyanjin,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/core-ui/bert-e/doc/user).





*Status report is not available.*

2019-11-12 11:20 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @chengyanjin

* @rachedbenmustapha

* @nicolas2bert

* @monpote

2019-11-12 17:09 UTC, carlito-scality requested changes

2019-11-12 17:09 UTC, carlito-scality commented on src/lib/components/button/Button.component.js
> +        cursor:pointer;
IMO, we do not need it here.

2019-11-12 17:09 UTC, carlito-scality commented on src/lib/components/button/Button.component.js
> +        cursor:pointer;
IMO, we do not need it here

2019-11-12 17:10 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @chengyanjin

* @rachedbenmustapha

* @nicolas2bert

* @monpote





The following reviewers are expecting changes from the author, or must review again:

* @carlito-scality

2019-11-13 07:44 UTC, ChengYanJin commented on src/lib/components/button/Button.component.js
> +        cursor:pointer;
You are right, thanks!

2019-11-13 07:57 UTC, carlito-scality approved these changes

2019-11-13 07:57 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @chengyanjin

* @rachedbenmustapha

* @nicolas2bert

* @monpote

2019-11-13 10:53 UTC, carlito-scality commented
/approve

2019-11-13 10:53 UTC, bert-e commented
# Not Author



I'm afraid I cannot do that, @carlito-scality:

Only the author of the pull request @chengyanjin can use this command.

Please **delete** the corresponding comment so I can move on.

2019-11-13 10:54 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @chengyanjin

* @rachedbenmustapha

* @nicolas2bert

* @monpote

2019-11-13 11:01 UTC, ChengYanJin commented
/approve

2019-11-13 11:01 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-11-14 13:44 UTC, carlito-scality commented
/wait

2019-11-14 14:26 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue None.

Goodbye chengyanjin.

2019-11-14 14:26 UTC, merged