Add CircularProgressBar
scality/core-ui pull request #138
Opened 2019-11-19 19:17 UTC by felipebrunetti94

**Component**:
CircularProgressBar
**Description**:
Add  circular progress bar
**Design**:
You can use custom color or default color for the fill bar

---
Closes: #115

2019-11-19 21:31 UTC, boniattirodrigo commented on src/lib/components/circularprogressbar/CircularProgressBar.component.js
> +function CircularProgressBar({ label, percent, title, color, ...rest }: Props) {
I don't see you using `rest`. I guess you can remove it.

2019-11-19 21:36 UTC, boniattirodrigo commented on src/lib/components/circularprogressbar/CircularProgressBar.component.style.js
> +  color: ${props => mergeTheme(props.theme, defaultTheme).text};
I see you using this piece of code twice. Couldn't you reuse it?

2019-11-22 10:56 UTC, carlito-scality commented
@felipebrunetti94 : reviewing

2019-11-22 13:43 UTC, carlito-scality requested changes

2019-11-22 13:43 UTC, carlito-scality commented on src/lib/index.js
> -  Chips
Please leave Chips there

2019-11-22 13:43 UTC, carlito-scality commented on src/lib/components/circularprogressbar/CircularProgressBar.component.js
> +  label?: string,
It would be more generic if you replace `label` by `props.children`

2019-11-22 13:43 UTC, carlito-scality commented on src/lib/components/circularprogressbar/CircularProgressBar.component.js
> +        <h3>{label}</h3>
Idem, Replace those labels by `props.children` to be more generic

2019-11-22 13:43 UTC, carlito-scality commented on src/lib/components/circularprogressbar/CircularProgressBar.component.js
> +  id?: string,
`id` can be remove here. If you want to have an `id`, you can pass it through `...rest`

2019-11-22 13:43 UTC, carlito-scality commented on src/lib/components/circularprogressbar/CircularProgressBar.component.js
> +function CircularProgressBar({ label, percent, title, color, ...rest }: Props) {
you can leave it there and use it here:
`<CircularProgressBarContainer percent={percent} color={color} className="sc-circularprogressbar" {...rest} >`
So you can pass `id` or everything you want to

2019-11-22 13:43 UTC, carlito-scality commented on src/lib/components/circularprogressbar/CircularProgressBar.component.js
> +        <circle cx="70" cy="70" r="70"></circle>
Please don't use fixed size. we should have `radius` as a props so we can support different sizes.
And you can use `radius` to compute:
```
const CIRCUMFERENCE = Math.PI * (radius * 2);

strokeDasharray: CIRCUMFERENCE,
strokeDashoffset: ((100 - percent) / 100) * CIRCUMFERENCE
```

2019-11-22 13:43 UTC, carlito-scality commented on src/lib/components/circularprogressbar/CircularProgressBar.component.style.js
> +export const Number = styled.div`
Please rename `Number` to `Label` for example

2019-11-22 13:43 UTC, carlito-scality commented on src/lib/components/circularprogressbar/CircularProgressBar.component.style.js
> +    font-size: 30px;
please use our predefined theme

2019-11-22 13:43 UTC, carlito-scality commented on src/lib/components/circularprogressbar/CircularProgressBar.component.style.js
> +    font-weight: 700;
Idem, please use our predefined theme

2019-11-22 13:43 UTC, carlito-scality commented on src/lib/components/circularprogressbar/CircularProgressBar.component.style.js
> +    stroke-width: 10;
`stroke-width` should be be defined as a prop (ex: circleThickness). You can put a default value (ex: 10)

2019-11-22 13:43 UTC, carlito-scality commented on src/lib/components/circularprogressbar/CircularProgressBar.component.style.js
> +    stroke-dasharray: 440;
440? How does it come from? `Math.PI * (70 * 2)` ?

2019-12-09 11:29 UTC, carlito-scality commented
@felipebrunetti94 do you want some help for this PR?

2019-12-09 14:44 UTC, felipebrunetti94 commented
@carlito-scality , sorry about the wait, I was working on other issues and forgot this one. I will finish it today. :D

2019-12-19 16:18 UTC, ChengYanJin commented
Hi @felipebrunetti94,
Wondering do you have time to address the review from us?
thanks

2019-12-26 12:33 UTC, carlito-scality commented
@felipebrunetti94 Hey! I will resume your PR if you don't mind since we need this component done very quickly :)

2019-12-26 21:57 UTC, felipebrunetti94 commented
I'm very sorry @carlito-scality ,couldn't find time to work on this PR.

2019-12-27 07:59 UTC, carlito-scality commented
> I'm very sorry @carlito-scality ,couldn't find time to work on this PR.

No problem, you helped us a lot already :)

2020-01-09 09:11 UTC, carlito-scality commented
Merged in https://github.com/scality/core-ui/pull/154

2020-01-09 09:11 UTC, closed without merging