WIP improve theme getter
scality/core-ui pull request #139
Opened 2019-11-25 14:41 UTC by rubynho

# WIP

Will solve #128 

**Component**:

**Description**:

**Design**:

**Breaking Changes**:

- [] Breaking Changes

---

Closes: #ISSUE_NUMBER

2019-11-27 14:38 UTC, carlito-scality requested changes
Hi! I have on change request about "defaultKey". Btw, you have a lot of syntax errors ;)
Thanks

2019-11-27 14:38 UTC, carlito-scality commented on src/lib/utils.js
> +  if (defaultKey && defaultKey(props)) return defaultKey(props)
IMO, we don't need to manage "defaultKey" here. Because we don't need to call `getThemeProp ` to return the `default` value ;)

2019-11-27 14:38 UTC, carlito-scality commented on src/lib/components/chips/Chips.component.js
> +      getTheme(props)[props.variant]
where does `getTheme` come from?

2019-11-27 15:52 UTC, rubynho commented
Hey @carlito-scality, sorry for the messy PR, it's not ready yet. I'll fix all the syntax errors and finish it soon!

2019-12-23 09:30 UTC, carlito-scality commented
> Hey @carlito-scality, sorry for the messy PR, it's not ready yet. I'll fix all the syntax errors and finish it soon!

@rubynho I'm gonna work this PR to finish it if you don't mind. we need to merge it as soon as possible

2020-01-03 15:05 UTC, carlito-scality commented
Merged in #153

2020-01-03 15:05 UTC, closed without merging