Feat/debounceinput
scality/core-ui pull request #146
Opened 2019-12-06 14:44 UTC by felipebrunetti94

**Component**:
DebounceInput 

**Description**:
Only implemented the input with the delay and minLength trigger, if everything is okay I can substitute the "react-debounce-input" for the new component.

**Design**:
Text input with value label next to it.

Closes: #103

2019-12-09 14:29 UTC, wenderjean commented on stories/index.js
> +import "./debounceinput";
You have a line ending problem here.

2019-12-16 13:11 UTC, carlito-scality requested changes
I think this component has to be isofunctional as the `react-debounce-input` so we can remove `react-debounce-input` dependency . IMO, the simplest way to do that is to re-write [react-debounce-input](https://github.com/nkbt/react-debounce-input/blob/master/src/Component.js) using react Hooks

2019-12-30 10:44 UTC, carlito-scality commented
Thanks to https://github.com/nkbt/react-debounce-input/commit/3c6719a91dd2854b378987fba9ceedb83dff5bea, we do not need this PR anymore since it is compatible with React 16.8

2020-01-09 09:12 UTC, carlito-scality commented
No need anymore thanks to https://github.com/scality/core-ui/pull/155

2020-01-09 09:12 UTC, closed without merging