Improvement: rework toggle
scality/core-ui pull request #321
Opened 2021-05-04 12:56 UTC by theocerutti

**Component**: Toggle

**Description**: Rework Toggle styling

**Design**:
![image](https://user-images.githubusercontent.com/44285344/117006302-8b09d680-ace8-11eb-8ce1-8ffda89140a0.png)

![image](https://user-images.githubusercontent.com/44285344/117006325-90ffb780-ace8-11eb-8868-d3db67998200.png)

**Breaking Changes**:

- [] Breaking Changes: I modified the wrapper ".sc-toggle" from div to label. 

Closes: #273

2021-05-04 12:56 UTC, bert-e commented
# Hello theocerutti,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/core-ui/bert-e/doc/user).





*Status report is not available.*

2021-05-04 12:56 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nicolas2bert

* @carlito-scality

* @monpote

* @chengyanjin

* @jbwatenbergscality

* @rachedbenmustapha

2021-05-04 15:34 UTC, Cuervino requested changes
1. The toggle itself is twice too big;
2. the circle is not round (issue on Figma also)
3. The action should be on the toggle (or also on the label), but not on the full line/container
![image](https://user-images.githubusercontent.com/28654802/117030319-c663cf80-acff-11eb-999d-00063701b99c.png)

The rest is nice!

2021-05-04 15:34 UTC, Cuervino commented on src/lib/components/toggle/Toggle.component.js
> +    height: 16.5px;
It would be better to have a fully round circle (same height and width)

2021-05-04 15:34 UTC, Cuervino commented on src/lib/components/toggle/Toggle.component.js
> +  width: 42px;
The target size of the toggle itself is 24px*14px (width * height).

With 42px width, the label is way too small compared to the toggle.

2021-05-04 15:34 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nicolas2bert

* @carlito-scality

* @monpote

* @chengyanjin

* @jbwatenbergscality

* @rachedbenmustapha





The following reviewers are expecting changes from the author, or must review again:

* @cuervino

2021-05-05 13:20 UTC, Cuervino requested changes
Seems almost good!
Maybe it's my browser, but it looks like it's not centered. Could you please check?
![image](https://user-images.githubusercontent.com/28654802/117147206-5021a480-adb5-11eb-9733-1a40ffb83a12.png)

2021-05-05 15:51 UTC, theocerutti commented
@Cuervino 
The problem is that if I center it totally at this zoom level the circle becomes non-centered when zoomed normally. It seems that the browser has trouble when the sizes are very small.

Currently, if we zoom "normally" the circle is centered:
![image](https://user-images.githubusercontent.com/44285344/117170522-6423d100-adca-11eb-91a8-dfb0c5394b22.png)
![image](https://user-images.githubusercontent.com/44285344/117170563-6ab24880-adca-11eb-9621-b275199d764c.png)

2021-05-06 13:29 UTC, JBWatenbergScality commented on src/lib/components/toggle/Toggle.component.js
> +  -webkit-transition: 0.4s;
Styled component automatically add vendor prefixing to css rules (https://styled-components.com/docs/basics#motivation) so this line can be removed

2021-05-06 13:29 UTC, JBWatenbergScality commented on src/lib/components/toggle/Toggle.component.js
> +    -webkit-transition: 0.4s;
This line can be removed

2021-05-10 08:06 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @chengyanjin

* @rachedbenmustapha

* @carlito-scality

* @monpote

* @jbwatenbergscality

* @nicolas2bert





The following reviewers are expecting changes from the author, or must review again:

* @cuervino

2021-05-18 15:51 UTC, Cuervino commented
It looks like the previous version, even if not aligned, was better.
1. On Firefox, there is a strange white corner on the top left
![image](https://user-images.githubusercontent.com/28654802/118683239-81609280-b801-11eb-98d4-67ee9fa8915a.png)

2. On Chrome, the rounding seems rather strange. On 100% zoom, one circle in the toggle looks like top aligned, the other looks like bottom aligned.
![image](https://user-images.githubusercontent.com/28654802/118683224-7d347500-b801-11eb-97ae-f5d561e129fa.png)

2021-05-20 07:17 UTC, Cuervino approved these changes
Top, LGTM!

2021-05-20 07:17 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @chengyanjin

* @rachedbenmustapha

* @carlito-scality

* @monpote

* @jbwatenbergscality

* @nicolas2bert

2021-05-20 07:30 UTC, JBWatenbergScality approved these changes

2021-05-20 07:31 UTC, theocerutti commented
@bert-e approve

2021-05-20 07:31 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-05-20 07:35 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue None.

Goodbye theocerutti.

2021-05-20 07:35 UTC, merged