PrettyBytes component
scality/core-ui pull request #343
Opened 2021-06-22 17:56 UTC by theocerutti

**Component**:  PrettyBytes

**Design**:
![image](https://user-images.githubusercontent.com/44285344/122975736-f6d8f900-d393-11eb-9b4f-21cf7c68d28e.png)

Closes: #336

2021-06-22 17:56 UTC, bert-e commented
# Hello theocerutti,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/core-ui/bert-e/doc/user).





*Status report is not available.*

2021-06-22 17:56 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @chengyanjin

* @rachedbenmustapha

* @carlito-scality

* @monpote

* @jbwatenbergscality

* @nicolas2bert

2021-06-24 09:40 UTC, Cuervino requested changes
The thousands separator should be the space (international norms), not the coma.

2021-06-24 09:40 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @chengyanjin

* @rachedbenmustapha

* @carlito-scality

* @monpote

* @jbwatenbergscality

* @nicolas2bert





The following reviewers are expecting changes from the author, or must review again:

* @cuervino

2021-07-02 09:10 UTC, Cuervino requested changes
For "KiB", I would take uppercase for the "K" instead of lowercase "k", as it's the Binary Prefix international standard.
https://en.wikipedia.org/wiki/Binary_prefix

2021-07-02 09:10 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @chengyanjin

* @nicolas2bert

* @carlito-scality

* @rachedbenmustapha

* @monpote

* @jbwatenbergscality





The following reviewers are expecting changes from the author, or must review again:

* @cuervino

2021-07-05 12:55 UTC, Cuervino approved these changes

2021-07-05 12:55 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @chengyanjin

* @nicolas2bert

* @carlito-scality

* @rachedbenmustapha

* @monpote

* @jbwatenbergscality

2021-07-12 11:36 UTC, JBWatenbergScality commented on src/lib/components/prettybytes/prettybytes.test.js
> +      { bytes: undefined, prettyBytes: '0 B' },
Should render `-` instead of `0 B`.

2021-07-12 11:36 UTC, JBWatenbergScality commented on src/lib/components/prettybytes/prettybytes.test.js
> +      { bytes: NaN, prettyBytes: '0 B' },
Should render `-` instead of `0 B`.

2021-07-12 11:36 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @monpote

* @chengyanjin

* @nicolas2bert

* @carlito-scality

* @rachedbenmustapha

* @jbwatenbergscality

2021-07-13 08:01 UTC, JBWatenbergScality approved these changes

2021-07-13 11:28 UTC, theocerutti commented
@bert-e approve

2021-07-13 11:29 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-07-13 11:32 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue None.

Goodbye theocerutti.

2021-07-13 11:32 UTC, merged