ChartTitleText: added ChartTitleText to Text components
scality/core-ui pull request #365
Opened 2021-09-08 13:15 UTC by JulienMeziere

**Component**: ChartTitleText

**Description**:

- added ChartTitleText to Text components
- Fixed dark mode on Text components
- Fixed code snippet for the Text components

**Breaking Changes**: none

- [] Breaking Changes

![image](https://user-images.githubusercontent.com/22881801/132516171-ae9c1ebc-80aa-4cc0-977f-3b42adad831b.png)

2021-09-08 13:15 UTC, bert-e commented
# Hello julienmeziere,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/core-ui/bert-e/doc/user).





*Status report is not available.*

2021-09-08 13:15 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @rachedbenmustapha

* @chengyanjin

* @nicolas2bert

* @jbwatenbergscality

* @monpote

2021-09-08 13:33 UTC, JBWatenbergScality requested changes

2021-09-08 13:33 UTC, JBWatenbergScality commented on src/lib/components/text/Text.component.js
> +  line-height: 1.429rem;
Could you please use `${spacing.sp20}` ?

2021-09-08 13:33 UTC, JBWatenbergScality commented on src/lib/components/text/Text.component.js
> +  letter-spacing: 0.143rem;
It can be replaced with `${spacing.sp2}`

2021-09-08 13:33 UTC, JBWatenbergScality commented on src/lib/components/text/Text.component.js
> +  line-height: 1.429rem;
It can be replaced with `${spacing.sp20}`

2021-09-08 13:33 UTC, JBWatenbergScality commented on src/lib/components/text/Text.component.js
> +  line-height: 1.429rem;
As it is the same value as BasicTextStyle, this can be removed from here

2021-09-08 13:33 UTC, JBWatenbergScality commented on src/lib/components/text/Text.component.js
> +  font-weight: 400;
As it is the same value as BasicTextStyle, this can be removed from here

2021-09-08 13:33 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @rachedbenmustapha

* @chengyanjin

* @nicolas2bert

* @jbwatenbergscality

* @monpote





The following reviewers are expecting changes from the author, or must review again:

* @jbwatenbergscality

2021-09-08 14:14 UTC, JBWatenbergScality requested changes

2021-09-08 14:14 UTC, JBWatenbergScality commented on src/lib/components/text/Text.component.js
>    font-size: 1rem;
This one can also be removed.

2021-09-08 14:52 UTC, JBWatenbergScality approved these changes

2021-09-08 14:52 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @carlito-scality

* @rachedbenmustapha

* @chengyanjin

* @nicolas2bert

* @jbwatenbergscality

* @monpote

2021-09-08 19:22 UTC, Cuervino approved these changes
lgtm

2021-09-09 12:18 UTC, JulienMeziere commented
/approve

2021-09-09 12:18 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-09-09 12:18 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue None.

Goodbye julienmeziere.

2021-09-09 12:18 UTC, merged