Fix selected tab behavior
scality/core-ui pull request #422
Opened 2022-04-14 14:46 UTC by AsmaaELM

Issue: https://scality.atlassian.net/browse/ARTESCA-4233

2022-04-14 14:46 UTC, bert-e commented
# Hello asmaaelm,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/core-ui/bert-e/doc/user).





*Status report is not available.*

2022-04-14 14:46 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @chengyanjin

* @rachedbenmustapha

* @carlito-scality

* @nicolas2bert

* @jbwatenbergscality

* @monpote

2022-04-22 08:24 UTC, ChengYanJin approved these changes

2022-04-22 08:29 UTC, AsmaaELM commented
/approve

2022-04-22 08:29 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-04-22 08:29 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue None.

Goodbye asmaaelm.

2022-04-22 08:29 UTC, merged

2022-04-22 08:37 UTC, JBWatenbergScality requested changes
The focus ring shouldn't be displayed on click on the element but only when using keyboard navigation