[PTFE-141] ✨ Implement GHAS
scality/core-ui pull request #593
Opened 2023-05-15 19:55 UTC by gaspardmoindrot

2023-05-15 19:55 UTC, bert-e commented
# Hello gaspardmoindrot,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://bert-e.scality.net/scality/core-ui/doc/user).





*Status report is not available.*

2023-05-15 19:55 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nicolas2bert

* @rachedbenmustapha

* @monpote

* @jbwatenbergscality

* @chengyanjin

2023-05-16 17:49 UTC, tcarmet requested changes

2023-05-16 17:49 UTC, tcarmet commented on .github/workflows/codeql.yaml
> +          languages: javascript
Shouldn't it be typescript?
```suggestion
          languages: typescript
```

2023-05-16 17:50 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nicolas2bert

* @rachedbenmustapha

* @monpote

* @jbwatenbergscality

* @chengyanjin





The following reviewers are expecting changes from the author, or must review again:

* @tcarmet

2023-05-16 20:49 UTC, tcarmet requested changes

2023-05-16 20:49 UTC, tcarmet commented on package-lock.json
> +        "@js-temporal/polyfill": "^0.4.3",
Why are we adding a new dependency?

2023-05-16 20:51 UTC, gaspardmoindrot commented on package-lock.json
> +        "@js-temporal/polyfill": "^0.4.3",
```suggestion
```

2023-05-17 23:11 UTC, tcarmet requested changes

2023-05-17 23:11 UTC, tcarmet commented on .github/workflows/codeql.yaml
> +          languages: typescript
My bad, rechecked the repo and as I see some .js file it should be both right?
```suggestion
          languages: typescript, javascript
```

2023-05-18 18:17 UTC, RachedBenMustapha approved these changes

2023-05-19 22:54 UTC, tcarmet approved these changes

2023-05-19 22:54 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nicolas2bert

* @rachedbenmustapha

* @monpote

* @jbwatenbergscality

* @chengyanjin

2023-05-23 08:34 UTC, MonPote approved these changes

2023-05-23 14:25 UTC, gaspardmoindrot commented
/approve

2023-05-23 14:25 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2023-05-23 14:26 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue PTFE-141.

Goodbye gaspardmoindrot.

2023-05-23 14:27 UTC, merged