Add eslint and remove yarn
scality/core-ui pull request #89
Opened 2019-09-20 14:33 UTC by MonPote

**Component**: ui, build, lint

**Description**:
- Add eslint
- Add commit hooks
- Remove yarn
- Add eslint to CI

---

Closes: #86

2019-09-20 14:33 UTC, bert-e commented
# Hello monpote,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/core-ui/bert-e/doc/user).





*Status report is not available.*

2019-09-20 14:33 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nicolas2bert

* @monpote

* @chengyanjin

* @carlito-scality

* @rachedbenmustapha

2019-09-20 15:34 UTC, carlito-scality requested changes

2019-09-20 15:34 UTC, carlito-scality commented on eve/main.yml
> +            npm install &&
it would be better to use ```npm ci```

2019-09-20 15:34 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nicolas2bert

* @monpote

* @chengyanjin

* @carlito-scality

* @rachedbenmustapha





The following reviewers are expecting changes from the author, or must review again:

* @carlito-scality

2019-09-23 09:07 UTC, carlito-scality approved these changes

2019-09-23 09:07 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nicolas2bert

* @monpote

* @chengyanjin

* @carlito-scality

* @rachedbenmustapha

2019-09-23 09:31 UTC, MonPote commented
@bert-e approve

2019-09-23 09:31 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-09-23 09:36 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue None.

Goodbye monpote.

2019-09-23 09:36 UTC, merged