Feature/multiselect component
scality/core-ui pull request #96
Opened 2019-10-04 18:43 UTC by edumoreira1506

**Component**:

**Description**:
Hello guys!

I tried to follow the pattern of project, but if have some change to do, I will fix it. So, the proposal was to made a new component, the multiselect component, and each option in multiselect component should had one field like "used" or no with one checkbox, each option too should have one "label" and one "value" like the example of the issue.

Detail: I created two buttons (add button and remove button) with pure css because of performance, both are very simple and I thought than don't needed use third libs.

**Design**:
![Screenshot from 2019-10-04 15-38-08](https://user-images.githubusercontent.com/49662698/66231474-fdee3e00-e6bc-11e9-8638-b5670a5ade8f.png)

---

Closes: #12 

-->

2019-10-04 18:43 UTC, bert-e commented
# Hello edumoreira1506,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/core-ui/bert-e/doc/user).





*Status report is not available.*

2019-10-07 09:27 UTC, carlito-scality commented
@edumoreira1506 Thanks. I'm reviewing it :)

2019-10-07 15:11 UTC, carlito-scality requested changes
> **Component**:
> 
> **Description**:
> Hello guys!
> 
> I tried to follow the pattern of project, but if have some change to do, I will fix it. So, the proposal was to made a new component, the multiselect component, and each option in multiselect component should had one field like "used" or no with one checkbox, each option too should have one "label" and one "value" like the example of the issue.
> 
> Detail: I created two buttons (add button and remove button) with pure css because of performance, both are very simple and I thought than don't needed use third libs.
> 
> **Design**:
> ![Screenshot from 2019-10-04 15-38-08](https://user-images.githubusercontent.com/49662698/66231474-fdee3e00-e6bc-11e9-8638-b5670a5ade8f.png)
> 
> Closes: #12
> 
> -->

Hello,
It looks good your component. However, this library contains only stateless components (See https://github.com/scality/core-ui#what-are-stateless-components).I just updated the README :) It means that those components do NOT manage state (except only for css rendering). Indeed, your component is a smart component ;) because it contains reducer, state and dispatch which should be implemented in the consuming project.

Based on that, the ```props``` of your component can look something lick below:
```
export type Props = {
  title: string,
  items: Array<Item>,
  options: Options,
  checkboxLabel: string,
};

export type Item = {
  label: string,
  description?: string,
  onRemove: any => void,  //on remove button click
  onChange: any => void  //on checkbox click
};

export type Options = {
  icon?: Node,
  placeholder?: string,
  optionsList: Array<Option>  // "Content of option"
  onSelect: any => void  //on option click
};

export type Option = {
  label: string,
  value: string | number
};

//pseudo code
function MultiSelect(props: Props) {
  return (
    <MultiSelectContainer>
        <MultiSelectHeader>{props.title}</MultiSelectHeader>
        <SelectedItemsContainer>{props.items.map(...)}</SelectedItemsContainer>
        <SelectContainer><Select options={props.options.optionsList}.../></SelectContainer>
    </MultiSelectContainer>
  );
}
```
- By the way, we need to reuse existing components like Checkbox (https://scality.github.io/core-ui/?path=/story/checkbox--default) for "Preferred" checkbox and Select (https://scality.github.io/core-ui/?path=/story/select--default) for "MultiSelectForm". Actually, the existing Select component does not support the idea to have the icon ("+" icon) inside the input. I will create a PR to add this feature.

Hopefully, it is clear for you. Feel free to ask questions. Thanks :)

2019-10-07 15:11 UTC, carlito-scality commented on src/lib/components/multiselect/MultiSelect.component.js
> +import React, { useReducer } from "react";
You should enable Flow by adding ```//@flow```

2019-10-07 15:15 UTC, carlito-scality commented on src/lib/components/multiselect/MultiSelect.component.js
> +MultiSelect.defaultProps = defaultProps;
You should remove defaultProps since it will be deprecated soon. You can use `Default Function arguments` instead

2019-10-10 12:59 UTC, edumoreira1506 commented
Thanks for the feedback! I believe then I fixed everything of you said. :thinking:

2019-10-10 15:59 UTC, carlito-scality commented
> Thanks for the feedback! I believe then I fixed everything of you said. 🤔

Hello!!! Thanks. I'm reviewing it and I will probably come up with some improvement commits :)

2019-10-15 10:56 UTC, merged